- name: My first playbook
  hosts: all
  vars_files:
  - "vars/additional_vars"
  tasks:
    - name: Ping check
      ping: 
    - name: Create a file
      # vars:
      #   filename: anotherhello
      command: sudo touch /home/ansible_controller/hello.txt

    - name: Install Packages
      become: yes
      apt:
        name: "{{ softwares }}"
        update_cache: yes
        state: present
      # loop:
      #   - jq
      #   - apache2
      #   - vim