- name: Ansible playbook
  hosts: all
  tasks:
    - name: Ping check
      ping: 
    - name: Updating App
      replace:
        path: /home/ansible_controller/src/App.js
        regexp: '\bWorld\b'
        replace: 'DevOps'
    - name: Run App
      command: sudo npm run start